#!/bin/bash

action=$1
shift

function usage(){
  echo "  Navigate to URL:"
  echo "    URL ITEM#"
  echo "      Searches for a URL in the todo line and launches it"
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

# Regular expression to match URLs
URL_REGEX='(http|https|ftp|ftps)://[^\s/$.?#].[^\s]*'

# Read the file to get the URL from the specified line number
URL=$(sed "$1!d" "$TODO_FILE" | grep -E -o "$URL_REGEX")

if [ "$URL" = "" ]; then
    LINE=$(sed "$1!d" "$TODO_FILE")
    if [ "$LINE" = "" ]; then
        echo "Error, no item #$1 found!"
    else
        echo "Error, no URL seen in item #$1!"
        echo "$LINE"
    fi
    exit 1
fi

# Launch the URL
cygstart "$URL"
